- file: /Users/tsantos/github/assignment2_python/sample_files/file1
  modified_date: '2017-11-25 12:39:07'
  description: 'File 1'

- file: /Users/tsantos/github/assignment2_python/sample_files/file2
  modified_date: '2017-11-25 13:50:57'
  description: 'File 2'
