- description: File 1
  file: /Users/tsantos/github/assignment2_python/sample_files/file1
  modified_date: '2017-11-25 12:39:07'

- description: File 2
  file: /Users/tsantos/github/assignment2_python/sample_files/file2
  modified_date: '2017-11-26 00:56:00'

- description: File 3
  file: /Users/tsantos/github/assignment2_python/sample_files/file3
  modified_date: '2017-11-25 22:57:18'
