{
    "file_descriptor": [
        {
            "modified_date": "2017-11-27 21:36:22", 
            "file_id": 1, 
            "file": "/Users/tsantos/github/assignment2_python/sample_files/file1", 
            "description": "File 1"
        }, 
        {
            "modified_date": "2017-11-27 21:36:20", 
            "file_id": 2, 
            "file": "/Users/tsantos/github/assignment2_python/sample_files/file2", 
            "description": "File 2"
        }
    ]
}