{
    "file_descriptor": {
        "modified_date": "2017-11-26 21:30:35", 
        "file_id": 2, 
        "file": "/Users/tsantos/github/assignment2_python/sample_files/file2", 
        "description": "File 2"
    }
}