{
  "file_descriptor": [
    {
      "description": "File 1",
      "file": "/Users/tsantos/github/assignment2_python/sample_files/file1",
      "file_id": 1,
      "modified_date": "2017-11-26 18:37:31"
    },
    {
      "description": "File 2",
      "file": "/Users/tsantos/github/assignment2_python/sample_files/file2",
      "file_id": 2,
      "modified_date": "2017-11-26 18:37:31"
    }
  ]
}
